# @title
# @since 2020/08/13
# @author ryota-suzuki

version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      -
        image: circleci/node:12.16.1

commands:
  setup_git_config:
    steps:
      - add_ssh_keys:
          fingerprints: "64:b4:26:2b:dc:7b:7a:24:17:98:bd:cd:ac:7d:b4:ea"
      - run: git config --global user.email "circleci@example.com"
      - run: git config --global user.name "circleci"
  restore_dependencies:
    steps:
      -
        restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_dependencies:
    steps:
      -
        save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            -
              ./node_modules

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run: npm run basics::bootstrap
      - save_dependencies
      - run: npm run test
  doc:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run: npm run basics::bootstrap
      - save_dependencies
      - run: npm run doc
      - setup_git_config
      - run: git add docs
      - run: git commit -m "[ci skip] build"
      - run: git push origin $CIRCLE_BRANCH

workflows:
  version: 2
  test:
    jobs:
      -
        test:
          filters:
            branches:
              ignore:
                - develop
  doc:
    jobs:
      -
        doc:
          filters:
            branches:
              only:
                - develop
