# @title
# @since 2020/08/13
# @author ryota-suzuki

version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.16.1

commands:
  restore_npm:
    steps:
      - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}

  save_npm:
    steps:
      - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ~/workspace/node_modules

jobs:
  executor: default
  steps:
    - checkout
    - run: echo "A first hello"
