# @title
# @since 2020/08/13
# @author ryota-suzuki

version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      -
        image: circleci/node:12.16.1

commands:
  restore_dependencies:
    steps:
      -
        restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

  save_dependencies:
    steps:
      -
        save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            -
              ./node_modules

jobs:
  doc:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run: npm install
      - save_dependencies
      - npm: npm run doc

workflows:
  version: 2
  test:
    jobs:
      -
        doc:
          filters:
            branches:
              only:
                - develop
