# @title
# @since 2020/08/13
# @author ryota-suzuki

version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.16.1

jobs:
  - test:
    executor: default
    steps:
      - checkout
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
