name: auto-merge

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
  # auto-merge:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.actor == 'dependabot[bot]' }}
  #   steps:
  #     - uses: ahmadnassri/action-dependabot-auto-merge@v2
  #       with:
  #         target: patch
  #         approve: false
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
